# Generated by Django 4.2.2 on 2023-06-16 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, null=True)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("Stationary", "Stationary"),
                            ("Elctronics", "Electronics"),
                            ("Food", "Food"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                ("quantity", models.PositiveBigIntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name="Prodcuts",
        ),
    ]
